

// primeiro esse 
POST http://localhost:4000/posts
content-type: application/json

{
    "name": "Alaina",
    "email": "Dawn.Bechtelar57@yahoo.com"
}


###

//depois esse 

GET  http://localhost:4000/posts

###


// depois esse 
PUT  http://localhost:4000/posts/1da6d602-fc8b-473d-8544-8e6d71debfb8
content-type: application/json

{
    "name": "Unique",
    "email": "Robin_Kirlin13@gmail.com"
    
}

###

// e o delete com id do usuario
DELETE   http://localhost:4000/posts/1da6d602-fc8b-473d-8544-8e6d71debfb8
